config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #my root page
  root 'welcome#index'

  #route to welcome index
  get 'welcome/index'

  #routes to posts
  resources :posts, only:[:index,:show] do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  #admin routes
  namespace :admin do
    resources :posts
    resources :projects
  end
  #routes to projects
  resources :projects 
  #routes to contacts
  resources :contacts, only:[:new,:create]
  resources :referals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #comments having many comments as commentable
  #and belonging dynamicaly to other models using polymorphism
  validates :content, presence: true
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  #hidden field to prevent span bots from filling in
  attribute :nickname,  :captcha  => true

  def headers
  	{
      :subject => "Contact Form",
      :to => "vamuigua@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :postimage, PostimageUploader
  validates :title, :content, presence: true
  #post having many comments as commentale
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
	mount_uploader :projectimage, ProjectimageUploader
	validates :title, :description,:link, presence: true
end

app/models/referal.rb
class Referal < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :referals
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
	before_action :find_post, only:[:show,:edit,:update,:destroy]

	def index
    @posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def new
    #create a new post in the form
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_path(@post), notice:"Article was successfully saved!"
    else
      render 'new',alert:"Unable to save your post."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice:"Article was successfully saved!"
    else
      render 'edit', alert:"Unable to save your article."
    end
  end

  def destroy
  	@post.destroy
  	redirect_to posts_path,alert:"Successfully deleted post"
  end

  private

  def post_params
    params.require(:post).permit(:title,:content,:postimage,:slug)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :check_for_admin
	#checks if current _user is nil or if current_user is an admin
	def check_for_admin
		if current_user.nil? || !current_user.is_admin?
			redirect_to root_path, alert:"You must be an admin to access this path"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable
  def index
    @comments = @commentable.comments
  end
  def new
    @comment = @commentable.comments.new
  end
  def create
    @comment = @commentable.comments.create(params[:comment].permit(:content))
    if @comment.save
      respond_to do |format|
        format.html{redirect_to @commentable, notice: "Comment created."}
        format.js
      end
    else
      render :new
    end
  end
  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html{redirect_to posts_path}
      format.js
    end
  end
  private
  def load_commentable
    resource, id = request.path.split('/')[1,2] #posts/1
    @commentable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only:[:show]
  before_action :authenticate_user!, except:[:index,:show]

  def index
    @posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def show
    @post = Post.find(params[:id])
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:title,:content,:postimage)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only:[:show]
  before_action :authenticate_user!, except:[:index,:show]

  def index
    @projects = Project.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def show
  end

  private

  def project_params
    params.require(:project).permit(:title,:description,:link,:slug)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/referals_controller.rb
class ReferalsController < ApplicationController
  before_action :find_referal,only:[:show,:destroy,:update]
  before_action :authenticate_user!, except:[:index,:show]

  def index
    @referals = Referal.all
  end

  def new
    @referal = Referal.new
  end

  def create
    @referal = Referal.new(referal_params)
    @referal.user = current_user

    if @referal.save
      respond_to do |format|
        format.html{redirect_to referals_path, notice:"Referal was successfully saved!"}
        format.js 
      end
    else
      render 'new',alert:"Unable to save your referal."
    end
  end

  def edit
        @referal = Referal.find(params[:id])
  end

  def update
    if @referal.update(referal_params)
      respond_to do |format|
        format.html{redirect_to referals_path, notice:"Referal was successfully removed!"}
        format.js 
      end
    end
  end

  def destroy
    @referal.destroy
    respond_to do |format|
        format.html{redirect_to referals_path, notice:"Referal was successfully removed!"}
        format.js 
      end
  end

  private

  def referal_params
    params.require(:referal).permit(:body,:slug)
  end

  def find_referal
    @referal = Referal.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(5).order("created_at desc")
		@projects = Project.all.limit(5).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #creating a method for markdown
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/referals_helper.rb
module ReferalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
	<%= comment.content%>
	<br>
	<br>
	<%= link_to "Delete Comment",[comment.commentable, comment],method: :delete, data:{confirm:'Are you sure?'}, remote: true, class: 'delete_comment_link'%>
</p>

app/views/comments/_comments.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1 style="color: rgba(0,0,0,0.8)">Comments</h1>
	<hr style="width: 100%">
	<% if @comments.any? %>
	<div id="comments">
		<%= render @comments %>
	</div>
	<%else%>
	<h4>Be the First to comment! 😊</h4>
	<%end%>
</div>

app/views/comments/_form.html.erb
<div class="skinny_wrapper wrapper_padding">
<%= form_for [@commentable, Comment.new], remote: true do |f| %>

<% if @comment.errors.any? %>
<div class="error_messages">
  <h2>Please correct the following errors.</h2>
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.label :content,"Write your comment here" %><br>
<%= f.text_area :content ,:required => true%>
<%= f.submit %>
<br>
<br>
<%= link_to "Cancel", :back, id:"cancel_link"%>

<% end %>
</div>

app/views/comments/create.js.erb
$('#new_comment').remove();
$('#new_comment_link').show();
$('#comments').append('<%= j render @comment %>');

app/views/comments/destroy.js.erb
$('.delete_comment_link').bind('ajax:success', function(){
	$(this).closest('p').fadeOut();
});

app/views/comments/index.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>Comments</h1>
	<% if @comments.any? %>
	<div id="comments">
		<% @comments.each do |comment| %>
		<div class="comment">
			<%= simple_format comment.content%>
		</div>
		<% end %>
	</div>
	<%else%>
	<h4>Be the First to comment! 😊</h4>
	<%end%>
	<p><%= link_to "New Comment", [:new, @commentable, :comment] %></p>
</div>

app/views/comments/new.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>New Comment</h1>
  <%= render "form" %>   
</div>

app/views/comments/new.js.erb
$('#new_comment_link').hide().after('<%= j render "form" %>');

app/views/contacts/create.html.erb
<h1 id="page_title">LETS GET IN TOUCH!</h1>
<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for your message!</h1>
	<p>I'll get back to you soon.😊</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">LETS GET IN TOUCH!</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name, required: true %>
	<br>
	<%= f.label :email %><br>
	<%= f.email_field :email, required: true %>
	<br>
	<%= f.label :message %><br>
	<%= f.text_area :message, as: :text,:required => true %>
	<div class="hidden">
		<%= f.label :nickname %><br>
		<%= f.text_field :nickname, hint: 'leave this field blank' %>
	</div>
	<%= f.submit 'Send Message', class: "button" %>
	<% end %>
</div>

app/views/referals/_form.html.erb
<div class="skinny_wrapper wrapper_padding">
	<%= form_for @referal, remote:true do |f| %>
	<% if @referal.errors.any? %>
	<h2><%= pluralize(@referal.errors.count,"error")%> prevented this referal from saving:</h2>
	<ul>
		<% @referal.errors.full_messages.each do |msg|%>
		<li><%= msg %></li>
		<%end%>
	</ul>
	<%end%>
	
	<%= f.label :Content %><br>
	<%= f.text_field :body,:required => true%>
	<br>
	<br>
	<%= f.submit %>
	<br>
	<br>
	<%= link_to "Cancel", :back, id:"cancel_link"%>
	<%end%>
</div>

app/views/referals/_referal.html.erb
<p>
<%=referal.body %><br>
<%if current_user && current_user.is_admin?%>
<%= link_to "Remove Referal", referal, method: :delete, data: {confirm: "Are you sure?"}, remote: true,class: 'delete_referal_link'%>
<hr>
<%end%>
</p>

app/views/referals/create.js.erb
$('#new_referal').remove();
$('#new_referal_link').show();
$('#all_referals').append('<%= j render @referal %>');

app/views/referals/destroy.js.erb
$('.delete_referal_link').bind('ajax:success', function(){
	$(this).closest('p').fadeOut();
});

app/views/referals/edit.html.erb
<h1>Referals#update</h1>
<p>Find me in app/views/referals/update.html.erb</p>

app/views/referals/index.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1 style="color: rgba(0,0,0,0.8)">Referals</h1>
	<hr style="width: 100%">
	<%= link_to "Add Referree", new_referal_path, id:"new_referal_link", remote: true%>
	<div id="all_referals">
		<%=render @referals%>
	</div>
</div>

app/views/referals/new.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>New Referal</h1>
	<%= render "form" %>
</div>

app/views/referals/new.js.erb
$('#new_referal_link').hide().after('<%=  j render("form") %>');