config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #my root page
  root 'welcome#index'

  #route to welcome index
  get 'welcome/index'

  #routes to posts
  resources :posts, only:[:index,:show] do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  #admin routes
  namespace :admin do
    resources :posts
    resources :projects
  end
  #routes to projects
  resources :projects 
  #routes to contacts
  resources :contacts, only:[:new,:create]
  resources :referals
end

app/models/project.rb
class Project < ApplicationRecord
	mount_uploader :projectimage, ProjectimageUploader
	validates :title, :description,:link, presence: true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :find_project, only:[:show,:edit,:update,:destroy]

  def index
    @projects = Project.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def new
    #create a new project in the form
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to project_path(@project), notice:"Project was successfully saved!"
    else
      render 'new',alert:"Unable to save your project."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice:"Project was successfully saved!"
    else
      render 'edit', alert:"Unable to save your project."
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path,alert:"Successfully deleted project"
  end

  private

  def project_params
    params.require(:project).permit(:title,:description,:link,:projectimage,:slug)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only:[:show]
  before_action :authenticate_user!, except:[:index,:show]

  def index
    @projects = Project.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def show
  end

  private

  def project_params
    params.require(:project).permit(:title,:description,:link,:slug)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="skinny_wrapper wrapper_padding">
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count,"error")%> prevented this project from saving:</h2>
		<ul>
			<% @project.errors.full_messages.each do |msg|%>
			<li><%= msg %></li>
			<%end%>
		</ul>
	<%end%>
	
	<%= f.label :title %><br>
	<%= f.text_field :title,:required => true%>

	<br>
	<br>

	<%= f.label :link,"Write your link here" %><br>
	<%= f.text_field :link,:required => true%>

	<br>
	<br>

	<%= f.label :description %><br>
	<%= f.text_area :description,:required => true%>

	<br>
	<br>

	
	<%= f.submit %>
	 

<%end%>
</div>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>Edit Project</h1>

<%= render "form" %>   
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've Built</h1>
<div id="posts_wrapper" class="skinny_wrapper">
<%if current_user && current_user.is_admin? %>
<%= link_to "New Project", new_admin_project_path, id:"new_comment_link"%>
<%end%>
	<% @projects.each do |project| %>
		<div class="post">
			<p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
			<h2><a href="#"><%= link_to project.title, project %></a></h2>
			<hr>
		</div>
	<% end %>
</div>

<%= will_paginate @projects %>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>New Project</h1>
	<%= render "form" %>
</div>

app/views/projects/show.html.erb
<div id="project_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
		<h1 style="color: rgba(0,0,0,0.8);"><%= @project.title %></h1>
		<%= image_tag @project.projectimage_url.to_s, id:'project_image'%>
		<hr>
	</header>
	<div id="description">
		<%=markdown @project.description %>
	</div>
	
	<div class="button_wrapper">
		<a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%=@project.title %></a>
	</div>
	<%if current_user && current_user.is_admin?%>
	<div id="admin_links">
		<%= link_to "Edit Project", edit_admin_project_path(@project) %>
		<%= link_to "Delete Project", admin_project_path(@project), method: :delete, data:{confirm:"Are you sure you want to delete this project?"}%>
	</div>
	<%end%>