config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #my root page
  root 'welcome#index'

  #route to welcome index
  get 'welcome/index'

  #routes to posts
  resources :posts, only:[:index,:show] do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  #admin routes
  namespace :admin do
    resources :posts
    resources :projects
  end
  #routes to projects
  resources :projects 
  #routes to contacts
  resources :contacts, only:[:new,:create]
  resources :referals
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :postimage, PostimageUploader
  validates :title, :content, presence: true
  #post having many comments as commentale
  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
	before_action :find_post, only:[:show,:edit,:update,:destroy]

	def index
    @posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def new
    #create a new post in the form
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_path(@post), notice:"Article was successfully saved!"
    else
      render 'new',alert:"Unable to save your post."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice:"Article was successfully saved!"
    else
      render 'edit', alert:"Unable to save your article."
    end
  end

  def destroy
  	@post.destroy
  	redirect_to posts_path,alert:"Successfully deleted post"
  end

  private

  def post_params
    params.require(:post).permit(:title,:content,:postimage,:slug)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only:[:show]
  before_action :authenticate_user!, except:[:index,:show]

  def index
    @posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def show
    @post = Post.find(params[:id])
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:title,:content,:postimage)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count,"error")%> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg|%>
			<li><%= msg %></li>
			<%end%>
		</ul>
	<%end%>
	
	<%= f.label :title %><br>
	<%= f.text_field :title,:required => true%>
		
	<br>
	<br>

	<%= f.label :postimage, "Post Picture"%><br>
	<%= f.file_field :postimage,:required => true%>

	<br>
	<br>

	<%= f.label :content,"Write your article here" %><br>
	<%= f.text_area :content,:required => true%>

	<br>
	<br>
	
	<%= f.submit %>
	 

<%end%>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>   

app/views/posts/index.html.erb
<h1 id="page_title">Stuff I've Written</h1>
<div id="posts_wrapper" class="skinny_wrapper">
<%if current_user && current_user.is_admin? %>
<%= link_to "New Post", new_admin_post_path ,id:"new_comment_link"%>
<%end%>
	<% @posts.each do |post| %>
	<div class="post">
		<p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
		<h2><a href="#"><%= link_to post.title, post_path(post) %></a></h2>
		<hr>
	</div>
	<% end %>
</div>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New Post</h1>

<%= render "form" %>   
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<%= image_tag @post.postimage_url.to_s, id:'post_image'%>
		<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @post.title %></h1>
		<hr>
	</header>
	<div id="content">
		<%=markdown @post.content %>
	</div>
	<%if current_user && current_user.is_admin?%>
	<div id="admin_links">
		<%= link_to "Edit Article", edit_admin_post_path(@post) %>
		<%= link_to "Delete Article", admin_post_path(@post), method: :delete, data:{confirm:"Are you sure you want to delete this post?"}%>
	</div>
	<%end%>
	<div id="share_box">
		<p>Share <%=@post.title%></p>
		<!-- Twitter -->
		<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @VictorAllen22 - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
		<!-- Facebook -->
		<a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
		<!-- Google Plus -->
		<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
	</div>
	<hr>
	<%= link_to "New Comment", new_post_comment_path(@post), id:"new_comment_link", remote: true%>
	<%= render "comments/comments" %>
</div>