config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #my root page
  root 'welcome#index'

  #route to welcome index
  get 'welcome/index'

  #routes to posts
  resources :posts, only:[:index,:show] do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  #admin routes
  namespace :admin do
    resources :posts
    resources :projects
  end
  #routes to projects
  resources :projects 
  #routes to contacts
  resources :contacts, only:[:new,:create]
  resources :referals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #comments having many comments as commentable
  #and belonging dynamicaly to other models using polymorphism
  validates :content, presence: true
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  #hidden field to prevent span bots from filling in
  attribute :nickname,  :captcha  => true

  def headers
  	{
      :subject => "Contact Form",
      :to => "vamuigua@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :postimage, PostimageUploader
  validates :title, :content, presence: true
  #post having many comments as commentale
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
	mount_uploader :projectimage, ProjectimageUploader
	validates :title, :description,:link, presence: true
end

app/models/referal.rb
class Referal < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :referals
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :check_for_admin
	#checks if current _user is nil or if current_user is an admin
	def check_for_admin
		if current_user.nil? || !current_user.is_admin?
			redirect_to root_path, alert:"You must be an admin to access this path"
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable
  def index
    @comments = @commentable.comments
  end
  def new
    @comment = @commentable.comments.new
  end
  def create
    @comment = @commentable.comments.create(params[:comment].permit(:content))
    if @comment.save
      respond_to do |format|
        format.html{redirect_to @commentable, notice: "Comment created."}
        format.js
      end
    else
      render :new
    end
  end
  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html{redirect_to posts_path}
      format.js
    end
  end
  private
  def load_commentable
    resource, id = request.path.split('/')[1,2] #posts/1
    @commentable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only:[:show]
  before_action :authenticate_user!, except:[:index,:show]

  def index
    @posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def show
    @post = Post.find(params[:id])
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:title,:content,:postimage)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only:[:show]
  before_action :authenticate_user!, except:[:index,:show]

  def index
    @projects = Project.all.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def show
  end

  private

  def project_params
    params.require(:project).permit(:title,:description,:link,:slug)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(5).order("created_at desc")
		@projects = Project.all.limit(5).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #creating a method for markdown
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/referals_helper.rb
module ReferalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="icon" href="../img/logo2.png">
		<title>Victor Allen</title>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!--JQuery.js-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<!--Google Fonts-->
		<link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
		<!--Font Awsome-->
		<!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"> -->
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		
		<!--NAVBAR SCROLL-->
		<header id="main_navigation" class="clearfix">
			<%= link_to "Victor Allen", root_path, class: "name" %>
			<nav>
				<ul id="meshow" class="dropdown-content">
					<li><%= link_to "<Articles>", posts_path %></li>
					<li><%= link_to "<Projects>", projects_path %></li>
					<!-- <li><a href="#skills">&lt;Skills&gt;</a></li> -->
					<li><%= link_to "<Contact>", new_contact_path %></li>
					<li><%= link_to "<Referals>", referals_path %></li>
				</ul>
				<div onclick="myFunction()" class="handle"><i class="fa fa-bars" aria-hidden="true"></i>&nbsp;Menu</div>
			</nav>
		</header>
		
		<%if notice%>
		<p class="notice"><%= notice %></p>
		<% elsif alert
		%>
		<p class="alert"><%= alert %></p>
		<%end%>
		<%= yield %>
		<footer id="main_footer">
			<p class="copyright">&copy;2017 Victor Allen</p><br>
			<p class="email"> <i class="fa fa-envelope" aria-hidden="true"></i>
 vamuigua@gmail.com</p>
			<nav>
				<a href="#"></a><b>&lt; Follow ME! &gt;</b></a>
				<a href="https://twitter.com/VictorAllen22" target="_blank"><i class="fa fa-twitter"></i></a>
				<a href="https://www.linkedin.com/in/victor-muigua-33a5b3124/" target="_blank"><i class="fa fa-linkedin"></i></a>
				<a href="https://medium.com/@vamuigua" target="_blank"><i class="fa fa-medium"></i></a>
				<a href="http://github.com/vamuigua" target="_blank"><i class="fa fa-github"></i></a>
			</nav>
		</footer>
		<!--Back to Top Button-->
		<a href="#0" class="cd-top">Top</a>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
	</body>
</html>